token = ""
STEP_ONE = 'step_one'
STEP_TWO = 'step_two'
STEP_THREE = 'step_three'
STEP_FOUR = 'step_four'
ACTION_ONE = 'action 1'
ACTION_TWO = 'action 2'
ACTION_THREE = 'action 3'
ACTION_FOUR = 'action 4'
